### ISSUE TITLE
resulting MEI is missing meiversion

### ISSUE THREAD

**Issue by rettinghaus** [cemfi/measure-detector#6]
Although `@meiversion` is optional, it would be good to specify the version of the MEI.

**Comment by sonovice** [comment]
The version is omitted on purpose to ensure compatibility with [cemfi/vertaktoid](https://github.com/cemfi/vertaktoid). Officially, it's version "3.0.0". We would have to fix it in Vertaktoid first, but since we are actively working on a replacement, the transition to "4.0.0" will be postponed for a little longer.

**Comment by rettinghaus** [comment]
Thanks! Perhaps it would be a good idea to have this info in the readme.

**Comment by sonovice** [comment]
I will add it, thanks!

**Comment by sonovice** [comment]
MEI is now compatible to v3 and v4.
